version: "3.8"

services:
  postgres_db:
    image: postgres:17
    container_name: merch_store_db
    env_file:
      - .env
    #environment:
    #  DSN: ${DSN}
    ports:
      - "5432:5432"
#    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "merch_store"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s
    volumes:
      - pg_data:/var/lib/postgresql/data

  default_migrate:
    env_file:
      - .env
    build:
      context: .
      dockerfile: migrations/Dockerfile
    container_name: merch_store_migrator
    depends_on:
      postgres_db:
        condition: service_healthy
    restart: on-failure
    #environment:
    #  MIGRATION_DIR: ./migrations
    #  MIGRATION_DSN: postgres_db://user:password@localhost:5432/merch_store?sslmode=disable
    volumes:
      - ./migrations:/migrations

  app:
    build: .
    container_name: merch_store_server
    restart: always
    depends_on:
      - postgres_db
    #environment:
    #  DSN: ${DSN}
    #  PORT: 8080
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"

volumes:
  pg_data:
