httpServer:
  port: 8080

postgres:
  dsn: 'postgres://user:password@localhost:5432/merch_store?sslmode=disable'

txManager:
  timeoutMs: 10
  maxRetries: 3

jwt:
  secret: 'secret'
  ttlMin: 180

logger:
  level: 'debug'
  logFile: 'logs/app.log'
