httpServer:
  port: 8080

postgres:
  dsn: 'postgres://postgres:postgres@localhost:5432/postgres'
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432
  db: 'postgres'
  sslMode: 'disable'
  timeoutSec: 3
  maxRetries: 3

txManager:
  timeoutSec: 3
  retryCount: 3

jwt:
  secret: 'secret'
  accessTtl: 15
  refreshTtl: 30

logger:
  level: 'debug'
  logFile: 'logs/app.log'
